source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/hacoma/iOS-Hacoma-Module-CocoaPods-Specs.git'

platform :ios, '11.0'
project 'APIService'
inhibit_all_warnings!
use_frameworks!

def hacomaExtensions
    pod 'HacomaExtensions', '1.0.2'
end

def hacomaNetwork
    pod 'HacomaNetwork', '1.0.2'
end

target :'Auth' do
    hacomaExtensions
    hacomaNetwork
end